# Generated by Django 4.1.8 on 2023-05-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_caverns_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='name',
            field=models.CharField(default='toast', max_length=255),
        ),
    ]
