# Generated by Django 4.1.8 on 2023-05-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_links_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='caverns',
            name='found',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='links',
            name='found',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
