# Generated by Django 4.1.8 on 2023-05-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_caverns_found_links_found'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caverns',
            name='data',
        ),
        migrations.AddField(
            model_name='caverns',
            name='gimp_file_ref',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
    ]
