# Generated by Django 4.1.8 on 2023-05-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_caverns_data_caverns_gimp_file_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='caverns',
            name='current',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
